# Generated by Django 5.1.4 on 2024-12-22 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_appointment_phone_number'),
        ('doctors', '0002_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateField(auto_now_add=True)),
                ('admission_required', models.BooleanField(default=False)),
                ('revisit_required', models.BooleanField(default=False)),
                ('lab_tests', models.TextField(blank=True, null=True)),
                ('medication_details', models.TextField(help_text='Details of medications prescribed.')),
                ('dosage_instructions', models.TextField(help_text='Dosage details (e.g., before food, after food, AM/PM).')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
