# Generated by Django 5.1.4 on 2025-01-06 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
