# Generated by Django 5.1.4 on 2025-01-12 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_doctor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='password',
        ),
    ]
